[mappings]
# Virtual Gamepad Buttons:
#   "btn_north"
#   "btn_south"
#   "btn_east"
#   "btn_west"
#   "btn_dpad_up"
#   "btn_dpad_down"
#   "btn_dpad_left"
#   "btn_dpad_right"
#   "btn_gripl"
#   "btn_gripl2"
#   "btn_gripr"
#   "btn_gripr2"
#   "btn_thumb"
#   "btn_thumb2"
#   "btn_thumbl"
#   "btn_thumbr"
#   "btn_tl"
#   "btn_tl2"
#   "btn_tr"
#   "btn_tr2"
#   "btn_base"
#   "btn_mode"
#   "btn_select"
#   "btn_start"
#   "disabled"
#
# Virtual Mouse Buttons:
#   "mouse_btn_left"
#   "mouse_btn_right"
#   "mouse_btn_middle"

# face buttons
btn_a = "btn_south"
btn_b = "btn_east"
btn_x = "btn_west"
btn_y = "btn_north"
# dpad buttons
btn_dpad_up    = "btn_dpad_up"
btn_dpad_down  = "btn_dpad_down"
btn_dpad_left  = "btn_dpad_left"
btn_dpad_right = "btn_dpad_right"
# left trigger and paddle buttons
btn_l1 = "btn_tl"
btn_l2 = "btn_tl2"
btn_l3 = "btn_thumbl"
btn_l4 = "btn_gripl"
btn_l5 = "btn_gripl2"
# right trigger and paddle buttons
btn_r1 = "btn_tr"
btn_r2 = "btn_tr2"
btn_r3 = "btn_thumbr"
btn_r4 = "btn_gripr"
btn_r5 = "btn_gripr2"
# menu buttons
btn_steam = "btn_mode"
btn_menu  = "btn_start"
btn_view  = "btn_select"
btn_quick = "btn_base"
# touchpad buttons
btn_touchpadl = "mouse_btn_right"
btn_touchpadr = "mouse_btn_left"

# Virtual Gamepad Axis:
#   "abs_x"
#   "abs_y"
#   "abs_z"
#   "abs_rx"
#   "abs_ry"
#   "abs_rz"
#   "disabled"
#
# Virtual Mouse Axis:
#   "mouse_rel_x"
#   "mouse_rel_y"

# trigger axis
axis_l2 = "abs_z"
axis_r2 = "abs_rz"
# left thumbstick axis
axis_thumbstickl_x = "abs_x"
axis_thumbstickl_y = "abs_y"
# right thumbstick axis
axis_thumbstickr_x = "abs_rx"
axis_thumbstickr_y = "abs_ry"

[virtual.gamepad]
name    = "Virtual Gamepad"
vid     = 0x0000
pid     = 0x0000
version = 1

[virtual.gamepad.rumble]
enabled = true
gain    = 6

# typically left thumbstick, x-axis
[virtual.gamepad.abs_x]
minimum = -32767
maximum = 32767
flipped = false

# typically left thumbstick, y-axis
[virtual.gamepad.abs_y]
minimum = -32767
maximum = 32767
flipped = true

# typically "l2"
[virtual.gamepad.abs_z]
minimum = 0
maximum = 32767
flipped = false

# typically right thumbstick, x-axis
[virtual.gamepad.abs_rx]
minimum = -32767
maximum = 32767
flipped = false

# typically right thumbstick, y-axis
[virtual.gamepad.abs_ry]
minimum = -32767
maximum = 32767
flipped = true

# typically "r2"
[virutal.gamepad.abs_rz]
minimum = 0
maximum = 32767
flipped = false

[virual.mouse]
name    = "Virtual Mouse"
vid     = 0x0000
pid     = 0x0000
version = 1
