FROM ubuntu:26.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install --no-install-recommends --yes \
        build-essential \
        ca-certificates \
        cmake \
        gcc-arm-linux-gnueabihf \
        git \
        rsync

# https://github.com/kraj/musl
# https://git.musl-libc.org/cgit/musl
RUN git clone https://github.com/kraj/musl /tmp/musl --branch v1.2.6 --depth 1 && \
    cd /tmp/musl && \
    AR=/usr/bin/arm-linux-gnueabihf-gcc-ar \
    CC=/usr/bin/arm-linux-gnueabihf-gcc    \
    LD=/usr/bin/arm-linux-gnueabihf-gcc    \
    NM=/usr/bin/arm-linux-gnueabihf-gcc-nm \
    RANLIB=/usr/bin/arm-linux-gnueabihf-gcc-ranlib \
    ./configure --enable-wrapper=gcc --prefix=/musl && \
    make -j install && \
    rm -rf /tmp/musl

ENV PATH="${PATH}:/musl/bin"
ENV CC=/musl/bin/musl-gcc
ENV LD=/musl/bin/musl-gcc

RUN git clone https://github.com/torvalds/linux /tmp/linux --branch v5.15 --depth 1 && \
    cd /tmp/linux && \
    make ARCH=arm INSTALL_HDR_PATH=/musl headers_install && \
    rm -rf /tmp/linux

