FROM ubuntu:26.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install --no-install-recommends --yes \
        build-essential \
        ca-certificates \
        cmake \
        git \
        rsync

# https://github.com/kraj/musl
# https://git.musl-libc.org/cgit/musl
RUN git clone https://github.com/kraj/musl /tmp/musl --branch v1.2.6 --depth 1 && \
    cd /tmp/musl && \
    AR=/usr/bin/ar         \
    CC=/usr/bin/gcc        \
    LD=/usr/bin/gcc        \
    NM=/usr/bin/nm         \
    RANLIB=/usr/bin/ranlib \
    ./configure --enable-wrapper=gcc --prefix=/musl && \
    make -j install && \
    rm -rf /tmp/musl

ENV PATH="${PATH}:/musl/bin"
ENV CC=/musl/bin/musl-gcc
ENV LD=/musl/bin/musl-gcc

RUN git clone https://github.com/torvalds/linux /tmp/linux --branch v6.1 --depth 1 && \
    cd /tmp/linux && \
    make ARCH=x86_64 INSTALL_HDR_PATH=/musl headers_install && \
    rm -rf /tmp/linux

